apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/bro-adm/home-lab.git
        revision: main
        directories:
          - path: "resources/*"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/bro-adm/home-lab.git
        targetRevision: main
        path: '{{path}}'  # e.g., resources/test-project
        kustomize:
          # optional: enable namePrefix, commonLabels, etc.
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

